services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 24.14.1
    container_name: backend-app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ../sistema-admin/
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app-react
      - /app-react/node_modules
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge